### ISSUE TITLE
Support SPA mode 

### ISSUE THREAD

**Issue by husayt** [nuxt-community/redirect-ssl#3]
From what I understand this doesn't work without node/express.

is SPA mode support in plans?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/redirect-ssl/issues/c2">#c2</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Hmm not totally but this middleware partially should work for spa when starting with `nuxt start` too. Are you trying to statically host generated files?

**Comment by husayt** [comment]
Yes, indeed I am looking solution for static website. Actually, I found what I needed.

https://github.com/nuxt/hackernews/blob/master/middleware/https.js

Will be very useful to at least mention this here or maybe make it part of the solution.

**Comment by pi0** [comment]
For static serving, most cloud providers like surge or CloudFlare support and also there is easy nginx configurations forcing SSL. While that https middleware works, i highly recommend using those high level configurations to enable **HTS** which is much more secure and stable for production use cases.

BTW PRs welcome for mentioning about middleware both here and in official docs repo.

**Comment by husayt** [comment]
Yes, indeed having server side redirect is preferred. But let's say I don't have that option and i have an spa, i need to get redirected from client.

I have tried what was in hackernews demo app, but that doesn't work. I hace registered the method below as middleware and req is always undefined.  Do I miss anything?

```
export default ({ isDev, req, redirect }) => {
        // Redirect to https
    if (!isDev && req) {
        const protocol = req.headers['x-forwarded-proto'] || (req.connection.encrypted ? 'https' : 'http')
        if (protocol === 'http') {
            return redirect(301, `https://${req.headers.host}${req.url}`)
        }
    }
}
```

**Comment by pSchaub** [comment]
nuxt supports `spa` mode: https://nuxtjs.org/api/configuration-mode/

**Comment by pi0** [comment]
Closing as unfortunately, this is outside scope of this package.

Actually SPA redirects also work but when using nuxt server (not static generated version)
