### ISSUE TITLE
redirect-ssl not working on generated content

### ISSUE THREAD

**Issue by htsoft** [nuxt-community/redirect-ssl#9]
Hi,  
i need to do an ssl redirect on my site to obtain from http://mysite.com to https://mysite.com  
All the contents are created with Nuxt and the final version is generated via:  
npm run generate command  

But when I try to upload the site to my server (with a simple Apache installation and a valid certificate) if I use http protocol it does not redirect to https protocol.

Could you please show me the exact passes to implement your plugin in this cases?

Kindly,
Roberto

**Comment by mickaelchanrion** [comment]
This won't work because you don't have a nuxt server running on generated projects
